export const dataList = [
    {
        _id: "1",
        title: "Men",
        src: "https://www.svgrepo.com/show/50532/shoes.svg",
        description: "Shop the new range of men's clothes, accessories, shoes, bags and more.",
        content:
          "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
        min_price: 124.9,
        max_price : 3849.3,
        colors: ["red", "black", "crimson", "teal"],
        count: 1,
        data: [
          {
            "id": "nUDo9mHZC9CD6U8UOZ2s",
            "name": "ADIDAS TOWEL LARGE",
            "brand": "Adidas",
            "views": "445455",
            "description": "Wrap yourself in the cotton comfort of this towel. The generous-sized towel is made of lightweight, quick-drying fabric that's soft and durable.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/nUDo9mHZC9CD6U8UOZ2s.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 749,
            "offer_amount": 7
          },
          {
            "id": "aaEVWeCLkX13zpNY1PQC",
            "name": "ULTRABOOST SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "These running shoes combine comfort and high-performance technology for a best-ever-run feeling. They have a stretchy knit upper that adapts to the changing shape of your foot as you run. Responsive midsole cushioning and a flexible outsole deliver a smooth and energised ride.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/aaEVWeCLkX13zpNY1PQC.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 3849.3,
            "offer_amount": 2
          },
          {
            "id": "4s5DBcmapTsSfJf4bGb5",
            "name": "FORUM 84 LOW ARWA SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "In the latest collaboration between adidas and Japanese streetwear label Human Made, we pay tribute to a true '70s classic. The Country shoe's original upper is done in premium suede and synthetic leather and paired with modern Boost cushioning. \"Gears for Futuristic Teenagers\" stands out on the signature 3-Stripes, and a reflective, heart-shaped print completes the look.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/4s5DBcmapTsSfJf4bGb5.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 2499,
            "offer_amount": 15
          },
          {
            "id": "UQ4DaRfJ0JJxr7greG2u",
            "name": "90S VALASION SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Show off heritage running style with a contemporary twist. These adidas shoes celebrate classic performance runners of the '90s as you grip unpredictable surfaces with confidence. Ultra-soft cushioning delivers step-in comfort from your first to last mile.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/UQ4DaRfJ0JJxr7greG2u.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1349.4,
            "offer_amount": 4
          },
          {
            "id": "POFUByQ75xTYBGAVfUlR",
            "name": "COPA 20.3 TURF BOOTS",
            "brand": "Adidas",
            "views": "445455",
            "description": "Play harder, win bigger. Always demand more. Your touch. Your team. In these football boots you'll transform them both. As you put on a show, stitching on the soft leather forefoot helps keep the ball close. A stretchy mesh quarter and built-in mono-tongue add lockdown while the foam midsole cushions every stride. Step it up in adidas Copa 20.3 Turf Boots.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/POFUByQ75xTYBGAVfUlR.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1557.5,
            "offer_amount": 9
          },
          {
            "id": "CFRUNeSLOBPTE4ZuI09V",
            "name": "DURAMO SL SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Variety keeps you motivated. For running, lifting or playing pickup games, these running shoes are all about versatile comfort. They have a lightweight build with pillow-like cushioning. No-sew overlays support the foot through quick bursts and lateral movements.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/CFRUNeSLOBPTE4ZuI09V.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1219,
            "offer_amount": 6
          },
          {
            "id": "CFRUNeSLOBPTE4ZuI09V",
            "name": "DURAMO SL SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Variety keeps you motivated. For running, lifting or playing pickup games, these running shoes are all about versatile comfort. They have a lightweight build with pillow-like cushioning. No-sew overlays support the foot through quick bursts and lateral movements.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/CFRUNeSLOBPTE4ZuI09V.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 999,
            "offer_amount": 7
          },
          {
            "id": "7Nz3k8nNNh4dCUpPCAqu",
            "name": "Mens Casual Premium Slim Fit T-Shirts",
            "brand": "Slim-fitting",
            "views": "445455",
            "description": "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/7Nz3k8nNNh4dCUpPCAqu.jpg",
            "created_by": "WtoQc2eOIaxkKVe1wdUW",
            "offer_price": 124.9,
            "offer_amount": 2
          },
          {
            "id": "UQ4DaRfJ0JJxr7greG2u",
            "name": "90S VALASION SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Show off heritage running style with a contemporary twist. These adidas shoes celebrate classic performance runners of the '90s as you grip unpredictable surfaces with confidence. Ultra-soft cushioning delivers step-in comfort from your first to last mile.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/UQ4DaRfJ0JJxr7greG2u.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1349.4,
            "offer_amount": 10
          },
          {
            "id": "CFRUNeSLOBPTE4ZuI09V",
            "name": "DURAMO SL SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Variety keeps you motivated. For running, lifting or playing pickup games, these running shoes are all about versatile comfort. They have a lightweight build with pillow-like cushioning. No-sew overlays support the foot through quick bursts and lateral movements.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/CFRUNeSLOBPTE4ZuI09V.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1219,
            "offer_amount": 0
          },
          {
            "id": "aaEVWeCLkX13zpNY1PQC",
            "name": "ULTRABOOST SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "These running shoes combine comfort and high-performance technology for a best-ever-run feeling. They have a stretchy knit upper that adapts to the changing shape of your foot as you run. Responsive midsole cushioning and a flexible outsole deliver a smooth and energised ride.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/aaEVWeCLkX13zpNY1PQC.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 3849.3,
            "offer_amount": 10
          },
          {
            "id": "nUDo9mHZC9CD6U8UOZ2s",
            "name": "ADIDAS TOWEL LARGE",
            "brand": "Adidas",
            "views": "445455",
            "description": "Wrap yourself in the cotton comfort of this towel. The generous-sized towel is made of lightweight, quick-drying fabric that's soft and durable.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/nUDo9mHZC9CD6U8UOZ2s.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 749,
            "offer_amount": 10
          },
          {
            "id": "4s5DBcmapTsSfJf4bGb5",
            "name": "FORUM 84 LOW ARWA SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "In the latest collaboration between adidas and Japanese streetwear label Human Made, we pay tribute to a true '70s classic. The Country shoe's original upper is done in premium suede and synthetic leather and paired with modern Boost cushioning. \"Gears for Futuristic Teenagers\" stands out on the signature 3-Stripes, and a reflective, heart-shaped print completes the look.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/4s5DBcmapTsSfJf4bGb5.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 2499,
            "offer_amount": 10
          },
          {
            "id": "POFUByQ75xTYBGAVfUlR",
            "name": "COPA 20.3 TURF BOOTS",
            "brand": "Adidas",
            "views": "445455",
            "description": "Play harder, win bigger. Always demand more. Your touch. Your team. In these football boots you'll transform them both. As you put on a show, stitching on the soft leather forefoot helps keep the ball close. A stretchy mesh quarter and built-in mono-tongue add lockdown while the foam midsole cushions every stride. Step it up in adidas Copa 20.3 Turf Boots.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/POFUByQ75xTYBGAVfUlR.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1557.5,
            "offer_amount": 5
          },
          {
            "id": "CFRUNeSLOBPTE4ZuI09V",
            "name": "DURAMO SL SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Variety keeps you motivated. For running, lifting or playing pickup games, these running shoes are all about versatile comfort. They have a lightweight build with pillow-like cushioning. No-sew overlays support the foot through quick bursts and lateral movements.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/CFRUNeSLOBPTE4ZuI09V.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1219,
            "offer_amount": 4
          },
          {
            "id": "aaEVWeCLkX13zpNY1PQC",
            "name": "ULTRABOOST SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "These running shoes combine comfort and high-performance technology for a best-ever-run feeling. They have a stretchy knit upper that adapts to the changing shape of your foot as you run. Responsive midsole cushioning and a flexible outsole deliver a smooth and energised ride.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/aaEVWeCLkX13zpNY1PQC.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 3849.3,
            "offer_amount": 2
          },
          {
            "id": "nUDo9mHZC9CD6U8UOZ2s",
            "name": "ADIDAS TOWEL LARGE",
            "brand": "Adidas",
            "views": "445455",
            "description": "Wrap yourself in the cotton comfort of this towel. The generous-sized towel is made of lightweight, quick-drying fabric that's soft and durable.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/nUDo9mHZC9CD6U8UOZ2s.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 749,
            "offer_amount": 7
          },
          {
            "id": "UQ4DaRfJ0JJxr7greG2u",
            "name": "90S VALASION SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Show off heritage running style with a contemporary twist. These adidas shoes celebrate classic performance runners of the '90s as you grip unpredictable surfaces with confidence. Ultra-soft cushioning delivers step-in comfort from your first to last mile.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/UQ4DaRfJ0JJxr7greG2u.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1359.4,
            "offer_amount": 0
          },
          {
            "id": "4s5DBcmapTsSfJf4bGb5",
            "name": "FORUM 84 LOW ARWA SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "In the latest collaboration between adidas and Japanese streetwear label Human Made, we pay tribute to a true '70s classic. The Country shoe's original upper is done in premium suede and synthetic leather and paired with modern Boost cushioning. \"Gears for Futuristic Teenagers\" stands out on the signature 3-Stripes, and a reflective, heart-shaped print completes the look.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/4s5DBcmapTsSfJf4bGb5.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 2499,
            "offer_amount": 7
          },
          {
            "id": "POFUByQ75xTYBGAVfUlR",
            "name": "COPA 20.3 TURF BOOTS",
            "brand": "Adidas",
            "views": "445455",
            "description": "Play harder, win bigger. Always demand more. Your touch. Your team. In these football boots you'll transform them both. As you put on a show, stitching on the soft leather forefoot helps keep the ball close. A stretchy mesh quarter and built-in mono-tongue add lockdown while the foam midsole cushions every stride. Step it up in adidas Copa 20.3 Turf Boots.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/POFUByQ75xTYBGAVfUlR.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1557.5,
            "offer_amount": 5
          },
          {
            "id": "aaEVWeCLkX13zpNY1PQC",
            "name": "ULTRABOOST SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "These running shoes combine comfort and high-performance technology for a best-ever-run feeling. They have a stretchy knit upper that adapts to the changing shape of your foot as you run. Responsive midsole cushioning and a flexible outsole deliver a smooth and energised ride.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/aaEVWeCLkX13zpNY1PQC.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 3849.3,
            "offer_amount": 10
          },
          {
            "id": "CFRUNeSLOBPTE4ZuI09V",
            "name": "DURAMO SL SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Variety keeps you motivated. For running, lifting or playing pickup games, these running shoes are all about versatile comfort. They have a lightweight build with pillow-like cushioning. No-sew overlays support the foot through quick bursts and lateral movements.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/CFRUNeSLOBPTE4ZuI09V.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1219,
            "offer_amount": 9
          },
          {
            "id": "POFUByQ75xTYBGAVfUlR",
            "name": "COPA 20.3 TURF BOOTS",
            "brand": "Adidas",
            "views": "445455",
            "description": "Play harder, win bigger. Always demand more. Your touch. Your team. In these football boots you'll transform them both. As you put on a show, stitching on the soft leather forefoot helps keep the ball close. A stretchy mesh quarter and built-in mono-tongue add lockdown while the foam midsole cushions every stride. Step it up in adidas Copa 20.3 Turf Boots.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/POFUByQ75xTYBGAVfUlR.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1557.5,
            "offer_amount": 5
          },
          {
            "id": "4s5DBcmapTsSfJf4bGb5",
            "name": "FORUM 84 LOW ARWA SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "In the latest collaboration between adidas and Japanese streetwear label Human Made, we pay tribute to a true '70s classic. The Country shoe's original upper is done in premium suede and synthetic leather and paired with modern Boost cushioning. \"Gears for Futuristic Teenagers\" stands out on the signature 3-Stripes, and a reflective, heart-shaped print completes the look.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/4s5DBcmapTsSfJf4bGb5.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 2499,
            "offer_amount": 6
          },
          {
            "id": "nUDo9mHZC9CD6U8UOZ2s",
            "name": "ADIDAS TOWEL LARGE",
            "brand": "Adidas",
            "views": "445455",
            "description": "Wrap yourself in the cotton comfort of this towel. The generous-sized towel is made of lightweight, quick-drying fabric that's soft and durable.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/nUDo9mHZC9CD6U8UOZ2s.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 749,
            "offer_amount": 7
          },
          {
            "id": "UQ4DaRfJ0JJxr7greG2u",
            "name": "90S VALASION SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Show off heritage running style with a contemporary twist. These adidas shoes celebrate classic performance runners of the '90s as you grip unpredictable surfaces with confidence. Ultra-soft cushioning delivers step-in comfort from your first to last mile.",
            "category": "men",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/UQ4DaRfJ0JJxr7greG2u.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1359.4,
            "offer_amount": 7
          }
        ]
      },
      {
        _id: "2",
        title: "Women",
        src: "https://t4.ftcdn.net/jpg/01/60/09/33/240_F_160093318_E2eW5uihQem0GOpbCa7BGz6FjSHFg4wk.jpg",
        description: "A Unique Shopping Website With A Distinctive Tone Focusing On Women's Fashion.",
        content:
          "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
        min_price: 699,
        max_price : 1789,
        colors: ["red", "crimson", "teal"],
        count: 1,
        data: [
          {
            "id": "eKtiN4VqHRqVyXrvbKPA",
            "name": "ADIZERO RC 2.0 SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "When the starting gun goes off, these are the running shoes you want on your feet. Responsive cushioning offers a snappy feel and fast ride, while the locked-down fit keeps your stride steady. Built with ultra-light materials, they keep you feeling fast for your epic finishing kick.",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/eKtiN4VqHRqVyXrvbKPA.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1359,
            "offer_amount": 3
          },
          {
            "id": "gIN79Skq8nd2kb2WKn38",
            "name": "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
            "brand": "BIYLACLESEN",
            "views": "445455",
            "description": "Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/gIN79Skq8nd2kb2WKn38.jpg",
            "created_by": "WtoQc2eOIaxkKVe1wdUW",
            "offer_price": 699,
            "offer_amount": 4
          },
          {
            "id": "2g8KOWqAvcfW37lGoRfa",
            "name": "OZWEEGO SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Variety keeps you motivated. For running, lifting or playing pickup games, these running shoes are all about versatile comfort. They have a lightweight build with pillow-like cushioning. No-sew overlays support the foot through quick bursts and lateral movements.",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/2g8KOWqAvcfW37lGoRfa.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1789,
            "offer_amount": 12
          },
          {
            "id": "eKtiN4VqHRqVyXrvbKPA",
            "name": "ADIZERO RC 2.0 SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "When the starting gun goes off, these are the running shoes you want on your feet. Responsive cushioning offers a snappy feel and fast ride, while the locked-down fit keeps your stride steady. Built with ultra-light materials, they keep you feeling fast for your epic finishing kick.",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/eKtiN4VqHRqVyXrvbKPA.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1482.5,
            "offer_amount": 3
          },
          {
            "id": "eKtiN4VqHRqVyXrvbKPA",
            "name": "ADIZERO RC 2.0 SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "When the starting gun goes off, these are the running shoes you want on your feet. Responsive cushioning offers a snappy feel and fast ride, while the locked-down fit keeps your stride steady. Built with ultra-light materials, they keep you feeling fast for your epic finishing kick.",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/eKtiN4VqHRqVyXrvbKPA.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1482.5,
            "offer_amount": 7
          },
          {
            "id": "2g8KOWqAvcfW37lGoRfa",
            "name": "OZWEEGO SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Variety keeps you motivated. For running, lifting or playing pickup games, these running shoes are all about versatile comfort. They have a lightweight build with pillow-like cushioning. No-sew overlays support the foot through quick bursts and lateral movements.",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/2g8KOWqAvcfW37lGoRfa.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1789,
            "offer_amount": 0
          },
          {
            "id": "2g8KOWqAvcfW37lGoRfa",
            "name": "OZWEEGO SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Variety keeps you motivated. For running, lifting or playing pickup games, these running shoes are all about versatile comfort. They have a lightweight build with pillow-like cushioning. No-sew overlays support the foot through quick bursts and lateral movements.",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/2g8KOWqAvcfW37lGoRfa.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1789,
            "offer_amount": 7
          },
          {
            "id": "eKtiN4VqHRqVyXrvbKPA",
            "name": "ADIZERO RC 2.0 SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "When the starting gun goes off, these are the running shoes you want on your feet. Responsive cushioning offers a snappy feel and fast ride, while the locked-down fit keeps your stride steady. Built with ultra-light materials, they keep you feeling fast for your epic finishing kick.",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/eKtiN4VqHRqVyXrvbKPA.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1482.5,
            "offer_amount": 8
          },
          {
            "id": "2g8KOWqAvcfW37lGoRfa",
            "name": "OZWEEGO SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "Variety keeps you motivated. For running, lifting or playing pickup games, these running shoes are all about versatile comfort. They have a lightweight build with pillow-like cushioning. No-sew overlays support the foot through quick bursts and lateral movements.",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/2g8KOWqAvcfW37lGoRfa.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1789,
            "offer_amount": 5
          },
          {
            "id": "eKtiN4VqHRqVyXrvbKPA",
            "name": "ADIZERO RC 2.0 SHOES",
            "brand": "Adidas",
            "views": "445455",
            "description": "When the starting gun goes off, these are the running shoes you want on your feet. Responsive cushioning offers a snappy feel and fast ride, while the locked-down fit keeps your stride steady. Built with ultra-light materials, they keep you feeling fast for your epic finishing kick.",
            "category": "women",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/eKtiN4VqHRqVyXrvbKPA.jpeg",
            "created_by": "7fCMnbPmOARgwZJZuXnk",
            "offer_price": 1482.5,
            "offer_amount": 0
          }
        ],
      },
      {
        _id: "3",
        title: "Devices",
        src: "https://freesvg.org/img/1516906894.png",
        description: "Device Tools is used for security-relevant, highly resilent cloud native applications",
        content:
          "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
        min_price: 3999,
        max_price : 6999,
        colors: ["lightblue", "white", "crimson", "teal"],
        count: 1,
        data: [
          {
            "id": "sDimb534b9EuZmc8nvz0",
            "name": "Xiaomi Poco X3 NFC",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Dual Sim Smartphone 6.67 Inch- 6GB Ram- 128GB, Blue",
            "category": "devices",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/sDimb534b9EuZmc8nvz0.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 4399,
            "offer_amount": 4
          },
          {
            "id": "nO41h4T0yYllckXHBRWx",
            "name": "Xiaomi Redmi Note 10S\r",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Dual SIM Mobile - 6.43 Inches, 6G RAM, 128 GB, 4G LTE - Ocean Blue\r",
            "category": "devices",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/nO41h4T0yYllckXHBRWx.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 3999,
            "offer_amount": 2
          },
          {
            "id": "DEGbErL3uHYNYQ7iQWll",
            "name": "Xiaomi Mi 11 Lite",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Dual SIM Mobile - 6.55 inches, 128 GB, 8 GB RAM, 4G LTE - Bubblegum Blue",
            "category": "devices",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/DEGbErL3uHYNYQ7iQWll.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 5599,
            "offer_amount": 5
          },
          {
            "id": "j3pnnCU5AtoEvGtU7a8V",
            "name": "Xiaomi Mi 10T\r",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Dual SIM Mobile, 6.67 Inches, 128 GB, 8 GB RAM, 5G - Cosmic Black",
            "category": "devices",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/j3pnnCU5AtoEvGtU7a8V.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 6988,
            "offer_amount": 3
          },
          {
            "id": "j3pnnCU5AtoEvGtU7a8V",
            "name": "Xiaomi Mi 10T\r",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Dual SIM Mobile, 6.67 Inches, 128 GB, 8 GB RAM, 5G - Cosmic Black",
            "category": "devices",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/j3pnnCU5AtoEvGtU7a8V.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 6999,
            "offer_amount": 25
          },
          {
            "id": "DEGbErL3uHYNYQ7iQWll",
            "name": "Xiaomi Mi 11 Lite",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Dual SIM Mobile - 6.55 inches, 128 GB, 8 GB RAM, 4G LTE - Bubblegum Blue",
            "category": "devices",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/DEGbErL3uHYNYQ7iQWll.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 5499,
            "offer_amount": 3
          },
          {
            "id": "nO41h4T0yYllckXHBRWx",
            "name": "Xiaomi Redmi Note 10S\r",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Dual SIM Mobile - 6.43 Inches, 6G RAM, 128 GB, 4G LTE - Ocean Blue\r",
            "category": "devices",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/nO41h4T0yYllckXHBRWx.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 4199,
            "offer_amount": 12
          },
          {
            "id": "sDimb534b9EuZmc8nvz0",
            "name": "Xiaomi Poco X3 NFC",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Dual Sim Smartphone 6.67 Inch- 6GB Ram- 128GB, Blue",
            "category": "devices",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/sDimb534b9EuZmc8nvz0.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 4299,
            "offer_amount": 10
          }
        ],
      },
      {
        _id: "4",
        title: "Gadgets",
        src: "https://media.istockphoto.com/vectors/headset-icon-music-templates-vector-id1187826963?b=1&k=6&m=1187826963&s=170667a&w=0&h=J63bbF21Z332e9pkG2bKuBaK-VCtMZTEyaD7yxeAP8Y=",
        description: "Latest technology news daily, new best tech gadgets reviews which include mobiles, tablets, laptops.",
        content:
          "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
          min_price : 632,
          max_price : 680,
        colors: ["orange", "black", "crimson", "teal"],
        count: 1,
        data: [
          {
            "id": "Ob4MSIVYkmk8TikXoIzF",
            "name": "Xiaomi Mi True 2 Basic\r",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Wireless Stereo Bluetooth Earphones with Noise Cancelling BHR4089GL - White",
            "category": "gadgets",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/Ob4MSIVYkmk8TikXoIzF.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 680,
            "offer_amount": 7
          },
          {
            "id": "Ob4MSIVYkmk8TikXoIzF",
            "name": "Xiaomi Mi True 2 Basic\r",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Wireless Stereo Bluetooth Earphones with Noise Cancelling BHR4089GL - White",
            "category": "gadgets",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/Ob4MSIVYkmk8TikXoIzF.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 632,
            "offer_amount": 9
          }
        ],
      },
      {
        _id: "5",
        title: "Tools",
        src: "https://i.pinimg.com/originals/f9/97/0a/f9970aa4a916cc1379708d6e3035babd.jpg",
        description: "A tool is an object that can extend an individual's ability to modify features of the surrounding environment as video games.",
        content:
          "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
          min_price: 835,
          max_price : 849,
        colors: ["orange", "black", "crimson", "teal"],
        count: 1,
        data: [
          {
            "id": "3vWnj8225wL2WaoXp9QL",
            "name": "Xiaomi Mi Smart Band 6",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Fitness Tracker with AMOLED Display, 1.56 Inches - Black\r",
            "category": "tools",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/3vWnj8225wL2WaoXp9QL.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 835,
            "offer_amount": 11
          },
          {
            "id": "3vWnj8225wL2WaoXp9QL",
            "name": "Xiaomi Mi Smart Band 6",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Fitness Tracker with AMOLED Display, 1.56 Inches - Black\r",
            "category": "tools",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/3vWnj8225wL2WaoXp9QL.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 849,
            "offer_amount": 7
          }
        ],
      },
      {
        _id: "6",
        title: "Food & Drinks",
        src: "https://www.svgrepo.com/show/42950/fast-food.svg",
        description: "Find the best Food and Drinks near you on Yelp - see all Food and Drinks open now.",
        content:
          "Welcome to our channel Dev AT. Here you can learn web designing, UI/UX designing, html css tutorials, css animations and css effects, javascript and jquery tutorials and related so on.",
        min_price : 125,
        max_price : 879,
        colors: ["orange", "black", "crimson", "teal"],
        count: 1,
        data: [
          {
            "id": "Ob4MSIVYkmk8TikXoIzF",
            "name": "Xiaomi Mi True 2 Basic\r",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Wireless Stereo Bluetooth Earphones with Noise Cancelling BHR4089GL - White",
            "category": "gadgets",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/Ob4MSIVYkmk8TikXoIzF.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 680,
            "offer_amount": 7
          },
          {
            "id": "Ob4MSIVYkmk8TikXoIzF",
            "name": "Xiaomi Mi True 2 Basic\r",
            "brand": "Xiaomi",
            "views": "445455",
            "description": "Wireless Stereo Bluetooth Earphones with Noise Cancelling BHR4089GL - White",
            "category": "gadgets",
            "image_url": "https://storage.googleapis.com/ayz-eh.appspot.com/products_images/Ob4MSIVYkmk8TikXoIzF.jpg",
            "created_by": "Ow6ZotufDYDSupiUPuJ0",
            "offer_price": 632,
            "offer_amount": 9
          }
        ]
      }
]